server:
  port: '8081'

# DataSource
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/turnover?autoReconnect=true
    username: root
    password: f1soft@611

  jpa:
    properties:
      hibernate:
        use_sql_comments: true #주석/**/해서 QUERY 확인
        format_sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

      ddl-auto: none
#      ddl-auto: create
#spring.jpa.properties.hibernate.show_sql=true


logging.level:
  org.hibernate.SQL: debug
#? confirm
  org.hibernate.type: trace